branch-defaults:
  dev:
    environment: udagram-krasserp-image-filter-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-krasserp-image-filter-dev
  branch: null
  default_ec2_keyname: udagram-krasserp
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: udagram-phil-dev
  repository: null
  sc: git
  workspace_type: Application
commands:
  command1:
    command: pip install --upgrade pip
  command2:
    command: pip install --force-reinstall numpy==1.16.3
  command3:
    command: pip install --force-reinstall opencv-contrib-python